name: Build Linux amd64

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build for Linux (x86_64)
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libsoup-3.0-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu

      - name: Cache Rust build artifacts
        uses: swatinem/rust-cache@v2

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        with:
          args: --target x86_64-unknown-linux-gnu

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rasp-kiosk-linux-x86_64
          path: src-tauri/target/x86_64-unknown-linux-gnu/release/bundle
          if-no-files-found: error
